### ISSUE TITLE
Seaweed-Wrapped Orders (63931/63933)

### ISSUE THREAD

**Issue by Shadownflame** [Project-Epoch/bugtracker#8369]
1) Quest item vanishes when accepted and you don't get it back if you abandon the quest
2) Quest objective speaks of "Tidepriestess" but the NPC in the world is spelled "Tide Priestess" - inconsistent

**Comment by Kestrana** [comment]
Fixed the spelling issue https://github.com/Project-Epoch/epoch-core/pull/1600

**Comment by Bennylavaa** [comment]
![image](https://github.com/user-attachments/assets/48bff48b-515a-47fc-b8f9-8d0877281330)
![image](https://github.com/user-attachments/assets/45dc67bd-70d1-45af-bb19-9476067a6288)

@Kestrana It looks like the issue still exists in the quest text for 63931 and 63933

Also the quest item being consumed when taking the quest is the more important fix here seeing if you abandon it you need to find the item again.
